apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "opensrp-server-web.fullname" . }}
  labels:
    {{- include "opensrp-server-web.labels" . | nindent 4 }}
data:
  opensrp.keycloak.json: |
    {{ .Values.keycloak_json | toJson }}
  opensrp.context.xml: |
    {{- include "config.opensrp.context.xml" . | nindent 4 }}
  opensrp.properties: |
    {{- include "config.opensrp.properties" . | nindent 4 }}
  mybatis.properties: |
    {{- include "config.mybatis.deployment.properties" . | nindent 4 }}
  opensrp.web.xml: |
    {{- include "config.opensrp.web.xml" . | indent 4 }}
  opensrp.server.xml: |
    {{- include "config.opensrp.server.xml" . | indent 4 }}