apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "opensrp-server-web.fullname" . }}
  labels:
  {{- include "opensrp-server-web.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
  {{- include "opensrp-server-web.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
      {{- include "opensrp-server-web.podAnnotations" . | indent 8 }}
      labels:
    {{- include "opensrp-server-web.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "opensrp-server-web.serviceAccountName" . }}
      securityContext:
      {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: opensrp-server-config-properties
          configMap:
            name: {{ include "opensrp-server-web.fullname" . }}
        - name: opensrp-server-config-context
          configMap:
            name: {{ include "opensrp-server-web.fullname" . }}
        - name: opensrp-server-config-keycloak
          configMap:
            name: {{ include "opensrp-server-web.fullname" . }}
        - name: opensrp-server-mybatis-properties
          configMap:
            name: {{ include "opensrp-server-web.fullname" . }}
        - name: opensrp-server-config-web
          configMap:
            name: {{ include "opensrp-server-web.fullname" . }}
        - name: opensrp-server-config-server-xml
          configMap:
            name: {{ include "opensrp-server-web.fullname" . }}
        {{- if .Values.multimediaPvc.enabled }}
        - name: opensrp-server-multimedia-dir
          persistentVolumeClaim:
            claimName: {{ include "opensrp-server-web.fullname" . }}
        {{- end }}
        {{- if  .Values.extraVolumes }}
        {{- toYaml .Values.extraVolumes | nindent 8 -}}
        {{- end }}
      initContainers:
        - name: {{ .Chart.Name }}-mybatis
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: opensrp-server-mybatis-properties
              mountPath: /migrations/environments/deployment.properties
              subPath: mybatis.properties
          command: ["/opt/mybatis/mybatis-migrations-3.3.4/bin/migrate", "up", "--path=/migrations", "--env=deployment"]
          resources:
      {{- toYaml .Values.mybatis.resources | nindent 12 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: opensrp-server-config-properties
              mountPath: /usr/local/tomcat/webapps/opensrp/WEB-INF/classes/opensrp.properties
              subPath: opensrp.properties
            - name: opensrp-server-config-context
              mountPath: /usr/local/tomcat/webapps/opensrp/META-INF/context.xml
              subPath: opensrp.context.xml
            - name: opensrp-server-config-keycloak
              mountPath: /usr/local/tomcat/webapps/opensrp/WEB-INF/keycloak.json
              subPath: opensrp.keycloak.json
            - name: opensrp-server-config-web
              mountPath: /usr/local/tomcat/webapps/opensrp/WEB-INF/web.xml
              subPath: opensrp.web.xml
            - name: opensrp-server-config-server-xml
              mountPath: /usr/local/tomcat/conf/server.xml
              subPath: opensrp.server.xml
              {{- if .Values.multimediaPvc.enabled }}
            - name: opensrp-server-multimedia-dir
              mountPath: /opt/multimedia
              {{- end }}
              {{- if  .Values.extraVolumeMounts }}
              {{- toYaml .Values.extraVolumeMounts | nindent 12 }}
              {{- end }}
          {{- if  .Values.env }}
          env:
            {{- .Values.env  | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
          {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
          {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
      {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
      {{- toYaml . | nindent 8 }}
  {{- end }}
