{{- if .Values.multimediaPvc.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "opensrp-server-web.fullname" . }}
  labels:
    {{- include "opensrp-server-web.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.multimediaPvc.accessModes | nindent 4 }}
  volumeMode: {{ .Values.multimediaPvc.volumeMode }}
  resources:
    {{- toYaml .Values.multimediaPvc.resources | nindent 4 }}
  {{- if .Values.multimediaPvc.storageClassName }}
  storageClassName: {{ .Values.multimediaPvc.storageClassName }}
  {{- end }}
  {{- if .Values.multimediaPvc.selector }}
  selector:
    {{- toYaml .Values.multimediaPvc.selector | nindent 4 }}
  {{- end  }}
{{- end -}}