apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "openhim-console.fullname" . }}
  labels:
  {{- include "openhim-console.labels" . | nindent 4 }}
data:
  default-json: |
  {{- include "config.default.json" . | nindent 4 }}
