apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "opensrp-web.fullname" . }}
  labels:
    {{- include "opensrp-web.labels" . | nindent 4 }}
data:
  config.js.tpl: |
    {{- include "config.react.config.js" . | nindent 4 }}