apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "opensrp-web.fullname" . }}
  labels:
    {{- include "opensrp-web.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "opensrp-web.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- include "opensrp-web.podAnnotations" . | indent 8 }}
      labels:
        {{- include "opensrp-web.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "opensrp-web.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: opensrp-server-config-properties
          configMap:
            name: {{ include "opensrp-web.fullname" . }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: opensrp-server-config-properties
              mountPath: /etc/confd/templates/config.js.tmpl
              subPath: config.js.tpl
          env:
            {{- include "opensrp-web.containerEnvironmentVariables" . | nindent 12 }}
            {{- include "opensrp-web.optionalRedisEnvs" . | nindent 12 }}          
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
