apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "opensrp-web.fullname" . }}
  labels:
    {{- include "opensrp-web.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "opensrp-web.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "opensrp-web.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "opensrp-web.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: opensrp-server-config-properties
          configMap:
            name: {{ include "opensrp-web.fullname" . }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: opensrp-server-config-properties
              mountPath: /etc/confd/templates/config.js.tmpl
              subPath: config.js.tpl
          env:
            - name: EXPRESS_OPENSRP_AUTHORIZATION_URL 
              value: https://{{ .Values.shared_vars.keycloak_url }}/auth/realms/eusm-mg-staging/protocol/openid-connect/auth
            - name: EXPRESS_OPENSRP_ACCESS_TOKEN_URL
              value: https://{{ .Values.shared_vars.keycloak_url }}/auth/realms/eusm-mg-staging/protocol/openid-connect/token
            - name: EXPRESS_OPENSRP_CALLBACK_URL
              value: https://{{ .Values.shared_vars.app_domain_name }}/oauth/callback/OpenSRP/
            - name: EXPRESS_OPENSRP_USER_URL
              value: {{ .Values.express.opensrp_user_url }}
            - name: EXPRESS_OPENSRP_CLIENT_ID
              value: {{ .Values.shared_vars.opensrp_client_id }}
            - name: EXPRESS_OPENSRP_CLIENT_SECRET
              value: {{ .Values.shared_vars.opensrp_client_secret }}
            - name: EXPRESS_SESSION_NAME
              value: {{ .Values.express.session_name }}
            - name: EXPRESS_SESSION_SECRET
              value: {{ .Values.express.session_secret }}
            - name: EXPRESS_FRONTEND_OPENSRP_CALLBACK_URL
              value: https://{{ .Values.shared_vars.app_domain_name }}/fe/oauth/callback/opensrp
            - name: EXPRESS_REACT_BUILD_PATH
              value:  {{ .Values.express.react_build_path }}       
            - name: NODE_ENV
              value:  {{ .Values.express.node_env }}     
            - name: EXPRESS_FRONTEND_LOGIN_URL
              value:  {{ .Values.express.frontend_login_url }}
            - name: EXPRESS_OPENSRP_OAUTH_STATE
              value:  {{ .Values.express.opensrp_oauth_state }}   
            - name: EXPRESS_SESSION_PATH
              value:  {{ .Values.express.session_path }}  
            - name: EXPRESS_SESSION_LOGIN_URL
              value:  {{ .Values.express.session_login_url }} 
            - name: EXPRESS_SESSION_FILESTORE_PATH
              value:  {{ .Values.express.frontend_logout_url }} 
            - name: EXPRESS_FRONTEND_LOGOUT_URL
              value:  {{ .Values.express.session_filestore_path }}  
            - name: EXPRESS_PRELOADED_STATE_FILE
              value:  {{ .Values.express.preloaded_state_file }} 
            - name: REACT_APP_OPENSRP_API_BASE_URL
              value:  {{ .Values.express.preloaded_state_file }}                                                                                                                                                                                                                                        
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
