apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dhis2-fhir-adapter.fullname" . }}
  labels:
  {{- include "dhis2-fhir-adapter.labels" . | nindent 4 }}
data:
  application.yaml: |
    {{- include "config.server.application.yaml" . | nindent 4 }}
