apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dhis2-fhir-adapter.fullname" . }}
  labels:
    {{- include "dhis2-fhir-adapter.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "dhis2-fhir-adapter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- include "dhis2-fhir-adapter.podAnnotations" . | indent 8 }}
      labels:
        {{- include "dhis2-fhir-adapter.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "dhis2-fhir-adapter.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: dhis-fhir-adapter-application-properties
          configMap:
            name: {{ include "dhis2-fhir-adapter.fullname" . }}
        {{- if  .Values.extraVolumes }}
        {{- toYaml .Values.extraVolumes | nindent 8 -}}
        {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: dhis-fhir-adapter-application-properties
              mountPath: /app/services/fhir-adapter/application.yml
              subPath: application.yaml
              {{- if  .Values.extraVolumeMounts }}
              {{- toYaml .Values.extraVolumeMounts | nindent 12 }}
              {{- end }}
          {{- if .Values.env }}
          env:
            {{- .Values.env  | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
          {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
          {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
