{{- if .Values.mapperConfigImporterJob.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "instantohie-mcsd-mock-service.fullname" . }}-mapper
  labels:
     {{- include "instantohie-mcsd-mock-service.labels" . | nindent 4 }}
spec:
  backoffLimit: 3
  template:
    spec:
      initContainers:
        - name: check-openhim-core-status
          image: busybox:1.28
          command: ['sh', '-c', 'until telnet {{ .Values.openhimCoreConfiguration.host }} {{ .Values.openhimCoreConfiguration.port }}; do echo OpenHIM Core API not running yet; sleep 10; done;']
      containers:
        - name: mapper-config-importer
          image: jembi/instantohie-config-importer
          args:
            - sh
            - -c
            - wait-on -t 60000 https-get://{{ .Values.openhimCoreConfiguration.host }}:{{ .Values.openhimCoreConfiguration.port }}/heartbeat && node /importer/openhimConfig.js
          env:
            - name: NODE_TLS_REJECT_UNAUTHORIZED
              value: '0'
            - name: OPENHIM_API_HOSTNAME
              value: {{ .Values.openhimCoreConfiguration.host | quote }}
            - name: OPENHIM_API_PASSWORD
              value: {{ .Values.openhimCoreConfiguration.password | quote }}
            - name: OPENHIM_API_PORT
              value: {{ .Values.openhimCoreConfiguration.port | quote }}
            - name: OPENHIM_API_USERNAME
              value: {{ .Values.openhimCoreConfiguration.username | quote }}
          volumeMounts:
            - mountPath: /importer/openhim-import.json
              name: mapper-openhim-import-json
              subPath: openhim-import-json
            - mountPath: /importer/openhimConfig.js
              name: mapper-openhim-config-js
              subPath: openhim-config-js
      restartPolicy: OnFailure
      volumes:
        - name: mapper-openhim-import-json
          configMap:
            name: {{ include "instantohie-mcsd-mock-service.fullname" . }}
        - name: mapper-openhim-config-js
          configMap:
            name: {{ include "instantohie-mcsd-mock-service.fullname" . }}
{{- end }}