{{- if .Values.mcsdEndpointImporterJob.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "instantohie-mcsd-mock-service.fullname" . }}-mcsd
  labels:
  {{- include "instantohie-mcsd-mock-service.labels" . | nindent 4 }}
spec:
  backoffLimit: 3
  template:
    spec:
      initContainers:
        - name: check-mapper-status
          image: busybox:1.28
          command: ['sh', '-c', 'until telnet {{ .Values.openhimMediatorMappingConfig.host }} {{ .Values.openhimMediatorMappingConfig.port }}; do echo Mapping mediator not running yet; sleep 10; done;']
      containers:
        - name: mcsd-endpoint-importer
          image: jembi/instantohie-config-importer
          args:
            - sh
            - -c
            - wait-on -t 60000 http-get://{{ .Values.openhimMediatorMappingConfig.host }}:{{ .Values.openhimMediatorMappingConfig.port }}/uptime && node /importer/endpoint.js
          env:
            - name: MEDIATOR_HOST_NAME
              value: {{ .Values.openhimMediatorMappingConfig.host | quote }}
            - name: MEDIATOR_API_PORT
              value: {{ .Values.openhimMediatorMappingConfig.port | quote }}
          volumeMounts:
            - mountPath: /importer/endpoint.js
              name: mcsd-endpoint-js
              subPath: endpoint-js
            - mountPath: /importer/endpoint.json
              name: mcsd-endpoint-json
              subPath: endpoint-json
            - mountPath: /importer/endpoint-2.json
              name: mcsd-endpoint-2-json
              subPath: endpoint-2-json
      restartPolicy: OnFailure
      volumes:
        - name: mcsd-endpoint-js
          configMap:
            name: {{ include "instantohie-mcsd-mock-service.fullname" . }}
        - name: mcsd-endpoint-json
          configMap:
            name: {{ include "instantohie-mcsd-mock-service.fullname" . }}
        - name: mcsd-endpoint-2-json
          configMap:
            name: {{ include "instantohie-mcsd-mock-service.fullname" . }}
{{- end }}