{{- if and .Values.serviceAccount.create .Values.deployMcsdMockService -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "instantohie-mcsd-mock-service.serviceAccountName" . }}
  labels:
    {{- include "instantohie-mcsd-mock-service.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
