apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "opencr.fullname" . }}
  labels:
  {{- include "opencr.labels" . | nindent 4 }}
data:
  config-instant: |
  {{- include "config.config_instant.json" . | nindent 4 }}
  decision-rules: |
  {{- include "config.decisionRules.json" . | nindent 4 }}
  mediator: |
  {{- include "config.mediator.json" . | nindent 4 }}
