apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hapi-fhir.fullname" . }}
  labels:
  {{- include "hapi-fhir.labels" . | nindent 4 }}
data:
  hapi.application.yaml: |
    {{- include "config.server.application.yaml" . | nindent 4 }}
