apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dhis2.fullname" . }}
  labels:
  {{- include "dhis2.labels" . | nindent 4 }}
data:
  dhis2-conf: |
  {{- include "config.dhis.conf" . | nindent 4 }}
