apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dhis2.fullname" . }}
  labels:
    {{- include "dhis2.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "dhis2.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- include "dhis2.podAnnotations" . | indent 8 }}
      labels:
        {{- include "dhis2.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "dhis2.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: prepopulate-dhis-web-volume
          image: busybox
          command: ['sh', '-c', 'cp /config/dhis.conf /DHIS2_home']
          volumeMounts:
            - name: dhis-config-map
              mountPath: /config/dhis.conf
              subPath: dhis2-conf
            - name: dhis-web-volume
              mountPath: /DHIS2_home
          resources:
            {{- toYaml .Values.initResources | nindent 12 }}
      volumes:
        - name: dhis-config-map
          configMap:
            name: {{ include "dhis2.fullname" . }}
        - name: dhis-web-volume
          emptyDir: {}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: dhis-web-volume
              mountPath: /DHIS2_home
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
