apiVersion: v1
kind: Service
metadata:
  name: {{ include "openhim-core.fullname" . }}
  labels:
    {{- include "openhim-core.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.httpApiPort }}
      targetPort: http-api
      protocol: TCP
      name: http-api
    - port: {{ .Values.httpsApiPort }}
      targetPort: https-api
      protocol: TCP
      name: https-api
  selector:
    {{- include "openhim-core.selectorLabels" . | nindent 4 }}
